### ISSUE TITLE
Removing Layouts

### ISSUE THREAD

**Issue by GreenBeard** [dodekeract/manta-config-engine-app#1]
Removing Layouts says 1 number to small. e.g. If I click Layout 4 then hit Remove Layout 4 it says "Do you really want to delete layout 3? Type 'yes' to continue." It's a simple bug and otherwise pretty great. Also unrelated but are camera panning keys currently available?

**Comment by FlorianWendelborn** [comment]
No they're not currently available, but if you can list what camera panning options you'd like to have and (if you already know the corresponding commands) add the commands I'd be able to implement them in some minutes.

**Comment by FlorianWendelborn** [comment]
Could you explain why your idea is on that camera panning thing? I've never really used anything besides the normal edge-pan camera movement, so I don't really know where to start. Also: please use #2 for further discussion on that camera topic.
