### ISSUE TITLE
Support for complex cycles of functions

### ISSUE THREAD

**Issue by hookdump** [dodekeract/manta-config-engine-app#10]
It would be nice to facilitate the process of creating cycles like this:

```
alias hp1 CHANGE HP BARS TO 100; alias hp hp2
alias hp2 CHANGE HP BARS TO 200; alias hp hp3
alias hp3 CHANGE HP BARS TO 300; alias hp hp1
bind L hp
```

I use a ton of this in my custom written config, although much more complex than this example:
I have one key that cycles between "GENERIC", and a list of my favorite heros. Then, depending the selected hero, a key cycles between relevant HP Bars.

For example, when I start a match as AXE, I hit "L". That displays "GENERIC / es / axe / rubick".
Currently my "K" key cycles between HP bars 100/200/300/etc...

I hit "L" again. That displays "generic / ES / axe / rubick".

I hit "L" again. That displays "generic / es / AXE / rubick".
Ok, I have Axe selected. So now, my key "K" cycles the HP Bars between 250, 325, 450, 550. (Relevant numbers for his ultimate).

Then I have similar stuff for other heros, for some heros it's a combo damage minus 25% magic resistance, for others it's the ultimate damage, etc.

It would be pretty awesome to have a system to allow this. Generating the code is pretty simple. The difficult part would be desgining an comfortable UI to do this with the web app.
Let me know if you'd consider implementing this. If not, I might implement it myself and pull-request when done.

**Comment by FlorianWendelborn** [comment]
Does c8168665672d10ecab2e7a56caa39bc159a75072 fix this?

**Comment by hookdump** [comment]
This is pretty neat. Great work!

**Comment by FlorianWendelborn** [comment]
Closing this then, create a new issue if you need more features to do what you want with your autoexec.
