### ISSUE TITLE
More Camera Commands

### ISSUE THREAD

**Issue by FlorianWendelborn** [dodekeract/manta-config-engine-app#2]
See #1.
- [x] Move Up
- [x] Move Down
- [x] Move Left
- [x] Move Right
- [x] find other camera commands, this surely can't be it

**Comment by GreenBeard** [comment]
@dodekeract Talking about issue #1 I was only talking about panning, up, down, left, and right I'm currently unaware of any other directions

**Comment by FlorianWendelborn** [comment]
okay, will close this then for now, thanks
