### ISSUE TITLE
smartcast cancel

### ISSUE THREAD

**Issue by FlorianWendelborn** [dodekeract/manta-config-engine-app#28]
At the moment, there is no way to cancel a smartcast action, which makes the feature quite useless.

**Comment by Sembrani** [comment]
There is, however it is not necessarily intuitive, as you have to press one of the modifier keys (for a multi-layout keybinding) while still holding the ability key, OR you could bind a smartcast cancel onto a key

**Comment by FlorianWendelborn** [comment]
How would that smartcast-cancelling key work? In general I mean, since this config can take any form the user wants.

**Comment by Sembrani** [comment]
so the key is bound to: 
`"dota_ability_execute 1; bind key smartcast_1"`
where -smartcast_1 is aliased to quick-cast on release. Then the cancel button executes:
`alias "smartcast_1" "smartcast_reset_1"`
where smartcast_reset_1 is:
`alias smartcast_1 dota_ablitity_quick_cast 1`

**Comment by Sembrani** [comment]
basic logic, but can be implemented a lot nicer

**Comment by FlorianWendelborn** [comment]
Yeah, sounds like it would work. Need to see when I find time to do that fix.
