### ISSUE TITLE
fix shop visual glitch

### ISSUE THREAD

**Issue by FlorianWendelborn** [dodekeract/manta-config-engine-app#33]
[via Reddit](https://www.reddit.com/r/DotA2/comments/45lbum/advanced_autoexec_generator_update/czywkeg)

**Comment by garrett-low** [comment]
Use toggleshoppanel instead of show_sf_shop

**Comment by FlorianWendelborn** [comment]
Seems to fix this, thanks!

**Comment by FlorianWendelborn** [comment]
Fixed in dodekeract/manta-config-engine@a78917bfdc15d3b85694730c6a835cb64c108773
