### ISSUE TITLE
Layout Editor - Switching layout issue

### ISSUE THREAD

**Issue by MrX101** [dodekeract/manta-config-engine-app#34]
At the moment u can set a key to send you to new layout, but it doesn't auto set the same key to send you to the old layout.

So some users might just create a new layout, set the keybinds they want in that layout, but not know they need to set a key to go back to the default layout, and are thus then stuck in that layout when they press the button.

**Comment by FlorianWendelborn** [comment]
You are right, it probably needs better documentation.

Being able to not set a key to go back is a feature though, so I'm not 100% sure yet, how I want to solve this.

An option would be to separate the two kinds of layout keys into two binding categories. Like "combo layout" and "permanent layout" switch.

**Comment by MrX101** [comment]
I would suggest just auto binding the same key used to enter the layout to go back to the default layout. But only when the layout is created

the user can then manually change it afterwards.

Also add a warning message if a layout has no way to leave it.

**Comment by FlorianWendelborn** [comment]
Closing this as it is quite similar to #29. Use that issue for any further comments.
