### ISSUE TITLE
dota_ability_quick_cast 1 for self cast

### ISSUE THREAD

**Issue by garrett-low** [dodekeract/manta-config-engine-app#35]
"dota_ability_quick_cast 1" must be set for self cast to work
Either automatically include it in autoexec.cfg, or add an option to Gameplay Settings

**Comment by FlorianWendelborn** [comment]
There is a third way, the Manta way. The engine is actually smart enough to handle `dependencies`, so I can tell it that `SelfCast` needs `enable-selfcast` and it includes `enable-selfcast` exactly once into the `autoexec.cfg`. :)

**Comment by FlorianWendelborn** [comment]
Fixed in dodekeract/manta-config-engine@049c9571f842e2ed90bf368f76715f49a1d29767
