### ISSUE TITLE
Ping on map only working when alt modifier is set to specific key

### ISSUE THREAD

**Issue by milksplash** [dodekeract/manta-config-engine-app#40]
Alt modifier works as intended when it is binded to Tab, Capslock or Alt.
But the function of pinging on map doesn't work when alt modifier is binded to number keys or letter keys.
Pinging on minimap or other alt modifier function works flawlessly with alt modifier binded to any key.
Is this a game-side issue?

**Comment by FlorianWendelborn** [comment]
I'm quite sure, that's an issue of the game, not of Manta. Leaving this open, because there may be workarounds in the future.

Quite interesting, that it seems to work with Tab & Capslock. I assumed the behaviour was hard-coded into Dota 2.
