### ISSUE TITLE
Cycles sometimes include commands in preset.json

### ISSUE THREAD

**Issue by perks** [dodekeract/manta-config-engine-app#41]
Hey thanks for your good work :)

Just a note, it seems having Layout1 quickcast keys bound and then normal cast keys bound in Layout2 does not result in Layout1 having the quickcast functionality enabled.

Tested by starting lobby, opening console:

```
unbindball
exec autoexec.cfg
```

[preset.json](https://pastebin.com/crPgGvu1)

**Comment by perks** [comment]
Update: Also tried with default layout, not only does quick cast not work on layout 1, but layout 2 selfcast also only triggers a normal cast.

**Comment by FlorianWendelborn** [comment]
Will have a look into this tomorrow. Can you tell me what your ingame setting for "Double Tap Ability To Self-Cast" or something like that is? It might be related.

**Comment by FlorianWendelborn** [comment]
Also I think I found a side-bug.

```
"O": [
                    "cycle",
                    0,
                    [
                        "dota_health_per_vertical_marker 250",
                        "dota_health_per_vertical_marker 325",
                        "dota_health_per_vertical_marker 450",
                        "dota_health_per_vertical_marker 550"
                    ]
                ],
```

It shouldn't include all the commands. I need to know if you did anything with <kbd>O</kbd> and what you did. Might be two bugs in one.

**Comment by perks** [comment]
@dodekeract Hey so interesting enough, it turns out that `unbindall` doesn't unbind the QWER keys from the Dota 2 menu (they get reset). In addition, using right click to clear the keybinds doesn't persist after you exist from the menu, you have to bind one of the options to an unused key and attempt to remap the rest to that same key to unset them. Once you do that, it seems to work as intended (with the side consequence of one of your skills being mapped to a particular key).

As for the O mapping, I think its in the default preset! As far as I know I didn't map O to anything, or added any cycle schemas.

**Comment by FlorianWendelborn** [comment]
That <kbd>O</kbd> thing is in the default preset, yes. But it shouldn't include these commands in the preset. That's why I'm wondering how that is possible.

So you didn't delete the keybinds in your ingame settings? That's the issue. You need to. AFAIK Manta can't overwrite them otherwise. Even with `unbindall`. Tell me if it works when you remove them manually in the settings.

**Comment by perks** [comment]
@dodekeract Yeah, I had thought that right clicking to clear the keybinds in menu would be enough (it isn't, you have to some rebinding/clear tricks otherwise it gets reset as default QWEDFR).

But yeah as far those cycle commands getting into the preset I'm sorry I can't be more helpful, it might have been a state-dependent generated bug that my browser found itself in when I requested the download link.

Feel free to mark this one closed though and thank you!

**Comment by FlorianWendelborn** [comment]
I think I will leave this open for some days, since I haven't found out what triggered the second issue. It really shouldn't have been possible.

Will spoiler/remove your `preset.json` though, since it takes up so much space.
