### ISSUE TITLE
Move space binding to cmd

### ISSUE THREAD

**Issue by glebmachine** [dodekeract/manta-config-engine-app#48]
Hi! Manta is awesome, thank you!)

I'm trying to find a way to replace `space` binding with `cmd` on my mac.
Is it possible?

**Comment by FlorianWendelborn** [comment]
I currently don't have access to a device running DotA 2. Can you bind anything to command/windows-key in the ingame settings?

**Comment by glebmachine** [comment]
Nope(

**Comment by FlorianWendelborn** [comment]
What if you tick the setting _Allow Windows / Command key to be bound_ in the advanced hotkey section?

**Comment by FlorianWendelborn** [comment]
@glebmachine is the issue resolved?

**Comment by glebmachine** [comment]
Will try soon)

**Comment by FlorianWendelborn** [comment]
bump
