### ISSUE TITLE
Use a different custom_load_indicator

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine-app#49]
Please consider using a different custom_load_indicator like "sounds/ui/ui_barn_door_open_01.vsnd_c"

This suits the theme more (used to be old client start-up sound) in my opinion.

**Comment by FlorianWendelborn** [comment]
My original plan was to allow any sound to be used as a load indicator and allow users to set that in the app. As a temporary workaround you can just export the preset, change the value in the loadIndicator section of the preset and import it again, that should do the trick until I add UI for that.

Also: do you have any idea where I can find a list of all sounds? I would need that to add them.

**Comment by crimsonvspurple** [comment]
List is too huge and most sounds are useless for the purpose of a config app. What I'd suggest is to provide a dropdown of some selective sounds and an option for the user to write custom "string" in there if s/he desire so.

You can go to
- start dota 2 tools -> item tools -> asset browser -> filter -> sound
  to get a huge list.

**Comment by crimsonvspurple** [comment]
Here's a list of sounds that can be given by default:

```
sounds/ui/buttonrollover.vsnd
sounds/ui/buttonclickrelease.vsnd
sounds/ui/buttonclick.vsnd
sounds/ui/coins.vsnd
sounds/ui/coins_big.vsnd
sounds/ui/item_pickup_gem_shop.vsnd
sounds/ui/ping.vsnd
sounds/ui/select_action.vsnd
sounds/ui/speech_popup.vsnd
sounds/ui/ui_upgrade_ability_01.vsnd
sounds/ui/yoink.vsnd
sounds/ui/panorama/panorama_cancel_custom_lobby_01.vsnd
sounds/ui/panorama/panorama_custom_lobby_dialog_01.vsnd
sounds/ui/panorama/panorama_find_match_cancel_01.vsnd
sounds/ui/panorama/panorama_menu_activate_open_01.vsnd
sounds/ui/panorama/panorama_settings_slide_out_01.vsnd
sounds/ui/panorama/panorama_rollover_micro_01.vsnd
sounds/ui/panorama/panorama_select_md_01.vsnd
```

**Comment by FlorianWendelborn** [comment]
Thanks, will see what I can do when I'm back at home. I need a description too, but I guess the one given in the file names should be good enough.

I will try to implement this in 1 or 2 days.
