### ISSUE TITLE
Custom commend in Cycle has extra "

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine-app#50]
If you put custom command in cycle, the result is like

.....
alias custom_cycle_2_command_0 ""custom_command""    // Command 1
......

It should be "custom_command"

**Comment by FlorianWendelborn** [comment]
Thanks, will see what I can do to prevent that. It's probably bugged because I can't know what you put in the custom command, so I always use quotes there. Should be easy to fix though.

**Comment by crimsonvspurple** [comment]
May be just add two " at the start and end of the text field to make it obvious that the quotes will be included by default and a msg not to wrap the commands in quotes.

**Comment by FlorianWendelborn** [comment]
So you added the quotes yourself? If you don't enter them this issue is nonexistent? If that's the case I'll just add another help text there.

**Comment by crimsonvspurple** [comment]
I think so (have been making lots changes so kinda forgot). I tested adding without quotes and it works as intended. So yeah, just a help text would be fine I guess.

**Comment by crimsonvspurple** [comment]
This has some other issue I think. All my custom commands again have double quotes at start and at end _even though I didn't add them_.

The cycle collection element has it right but when adding them to a button, there is extra " which translates in to extra " in autoexec.

I'll post again if I can figure out exact repro.

**Comment by FlorianWendelborn** [comment]
I think it's when you enter a command which requires quotes around it. It will always insert one pair, but if it detects that the command would need quotes it doesn't check if it already got quotes. Is that consistent with what you've tested so far?

**Comment by crimsonvspurple** [comment]
I think I found the issue.

Take a valid json file with custom commands in cycle and import it.

Download the config. The json file inside the zip will have extra ". At least that's what happened to me a while ago.

**Comment by FlorianWendelborn** [comment]
Yeah, there is a secondary issue involved in this. The presets are never supposed to include the cycle commands in the actual cycle binding. They should only bind by ´cycle,id´. The unique part of this issue should be fixed. The secondary part can be found in #41.
