### ISSUE TITLE
Add sound+text notification option for custom command

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine-app#51]
When adding a custom command, say `dota_player_add_summoned_to_selection 1`, give option in the UI to add two more things with it (both optional):
1. select a sound (e.g., `sounds/ui/buttonrollover.vsnd`)
2. type a text (e.g., `Auto Select Summoned Units: TRUE`)

Resultant custom command can be something like:

`dota_player_add_summoned_to_selection 1; playsound sounds/ui/tutorial_ui_ding_01.vsnd_c; say_student Auto Select Summoned Units: TRUE`

**Comment by FlorianWendelborn** [comment]
I'd implement it by adding _bulk commands_ (like cycles, but all commands are executed on one keypress). Can't give an ETA though, since it's nothing I personally use and therefore not on my personal top list of things to fix.

**Comment by FlorianWendelborn** [comment]
Marking this as `low-priority` since it would also be fixed by fixing #12.
