### ISSUE TITLE
Binding to \ and kp_. has issues

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine-app#52]
Binding to \ is resulting ! for me (in preset/cfg file) which is wrong.

Binding to keypad . results in KP_. which the game console says is invalid.

**Comment by FlorianWendelborn** [comment]
Which keyboard layout are you talking about? Default QWERTY? Manta actually supports multiple keyboard layouts so I need to know. Also the files associated to them are easy to understand even without knowing how Manta works, so if you find that annoying or want to submit a pull request to fix it it would be quite easy for you to do. They're located somewhere in the source/keyboard-layouts folder if I remember correctly.

**Comment by crimsonvspurple** [comment]
https://github.com/dodekeract/manta-config-engine-app/blob/master/source/web/keyboard-layouts/en-rz.json#L81

\ is mapped to !

https://github.com/dodekeract/manta-config-engine-app/blob/master/source/web/keyboard-layouts/en-rz.json#L157

. is mapped to KP_.

I'm using an older model blackwidow ultimate (BW Ultimate 2012) which might be why these are happening. Cant confirm without testing with chroma model. Someone else might be able to help...

**Comment by crimsonvspurple** [comment]
After a bit more digging, it seems there is another issue.
; should be SEMICOLON
Otherwise console shows errors (during bind and during unbind)

KP_. should be KP_DEL

These apply to default and razer layouts.

**Comment by FlorianWendelborn** [comment]
Thanks, I had to guess on some keys since it's quite hard to find proper information for the less used keys, will also change that when I'm back home.
