### ISSUE TITLE
Using action item breaks the visual layout

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine-app#54]
If you bind action item, it results in ac-NaN.

There should not be any NaN and it also breaks the visual layout.

Call it aitem instead?

**Comment by FlorianWendelborn** [comment]
In case you're not familiar with JavaScript `NaN` occurs when you attempt to treat something as a number, which can't be treated as one. The flaw in that piece of code is that action item translates to `item,action` in Manta-App (if I remember correctly) and the code that displays it tries to display `item,castmode,number`. Should be an easy fix, will do that soon (if you want to do it instead, the code should be somewhere in main.jsx). Also I'd just call it Action or Act. I. depending on what looks/fits better.

Thanks for testing this so carefully.
