### ISSUE TITLE
Add An Icon

### ISSUE THREAD

**Issue by FlorianWendelborn** [dodekeract/manta-config-engine-app#64]
Best would be to find somebody who can do stuff like that.

I imagine something which is a combination of a manta-style, a cog or maybe something totally different like an `M`.

**Comment by crimsonvspurple** [comment]
![manta_config_version1](https://cloud.githubusercontent.com/assets/11375716/14144873/632859de-f6b3-11e5-8ecb-fa57d83187b1.png)
![manta_config_version2](https://cloud.githubusercontent.com/assets/11375716/14144872/63158304-f6b3-11e5-8f53-6b2ad4d62d86.png)

I think v1 is better.

**Comment by FlorianWendelborn** [comment]
Thanks, looks quite good. I also prefer the first version.

Would be nice if you could submit this as a pull-request to `https://github.com/dodekeract/manta-config-engine-app/tree/master/source/web/images` with the filename `icon.png` or `svg` in case you somehow managed to make this a vector image.

**Comment by FlorianWendelborn** [comment]
Closed because of #66.
