### ISSUE TITLE
Quickcast issue with "on key down" option

### ISSUE THREAD

**Issue by IlnurKhabibullin** [dodekeract/manta-config-engine-app#70]
Hi!

In dota i have "quickcast on key down" option disabled, so it should be smartcasts. With quickcasts that was set in dota it works fine. But as i rebind the button in configs (to whatever command and to quickcast back), it stops working at all.

So, i suppose that there is some difference between indota quickcast settings (i mean after game launch) and quickcast in configs.

I know, that manta offers it's own smartcasts, using combination of commands, but in that case i can't cancel it.

**Comment by FlorianWendelborn** [comment]
Related to #28.

What exactly is the issue? I don't really understand what's not working about the current implementation of QuickCast.

What stops working at all? The button? The onkeydown option?

**Comment by IlnurKhabibullin** [comment]
Well, sorry, if i didn't make myself clear, english is not my native language.

Without any config, in game itself, quickcasts with "on key down" option disabled work as they should(becomes smartcast). When i use "dota_ability_quickcast N" command in configs with "on key down" option disabled, button "N" doent work at all(neither as quick nor smart nor even normal). Same for "dota_item_quick_cast N" command. If i enable mentioned option, quickcast from config starts working as quickcast.

**Comment by FlorianWendelborn** [comment]
Okay, that's much easier to understand and quite weird too. Will see if I find any solution/command to fix this.

**Comment by IlnurKhabibullin** [comment]
Thanks in advance

**Comment by FlorianWendelborn** [comment]
Closed due to #73.
