### ISSUE TITLE
Rest In Pieces, Manta

### ISSUE THREAD

**Issue by FlorianWendelborn** [dodekeract/manta-config-engine-app#74]
There is reason to believe that both Manta and TheCore may be forbidden in tournaments after Manila.

Here is [a quite bad reddit source](https://www.reddit.com/r/DotA2/comments/4ksmrf/the_manila_major_brought_in_an_updated_ruleset/).

If anybody has a better source, I'd highly appreciate it.

related to loopuleasa/Dota2-TheCore-Config-Engine#159

**Comment by crimsonvspurple** [comment]
New update: A key input can no longer be bound to multiple console commands, except when cheats are on or spectating.

**Comment by FlorianWendelborn** [comment]
@crimsonvspurple yep, we dead now. Let's pray to RNGsus that Valve will revert this change and replace it with something more reasonable, like **forbidding to use multiple items/abilities in one autoexec tick**.

**Comment by crimsonvspurple** [comment]
I actually had a feeling that this would _officially_ be the case sooner or later. Refer to my post here: http://dev.dota2.com/showthread.php?t=50605&page=17&p=363301&viewfull=1#post363301

For what it is worth, I have setup my preset to minimize the damage. But I'd still miss these the most:
- Multiple Chatwheels
- Space as modifier key
- Toggle openmic; auto attack; auto select summon
