### ISSUE TITLE
Need Testing with GUI Installer

### ISSUE THREAD

**Issue by Aevyz** [dodekeract/manta-config-engine-app#75]
## Intro

Alright, as promised @dodekeract, I adapted the installer for Manta. Being rather silly, I hard coded windows, instead of using [System.getProperty()](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html), I will work on that. Hopefully, the libraries don't break on other OSs
## Task

I need some people to test it out. The installer will install in the following format: It will not overwrite any of your current files, unless you for some reason have them called the following:

Folders called:
- loop
- core
- manta
- tab

Autoexecs called
- core.cfg
- manta.cfg
- tab.cfg
- loop.cfg

![image](https://cloud.githubusercontent.com/assets/17731961/15522694/8e6a3afe-2214-11e6-8f06-be54dbbd1ed3.png)

Screnshot of GUI:
![image](https://cloud.githubusercontent.com/assets/17731961/15522712/a508ecec-2214-11e6-8e52-97c580631cc7.png)

Instructions should be fairly self-explanatory IMO. **!!!Only Windows Is Supported Until I Reprogram The Installer!!!**
## Github Link

https://github.com/AetherV/Dota2-Config-Installer
## Download
- https://github.com/AetherV/Dota2-Config-Installer/blob/master/Compiled/16-5-25%20Dota2%20Conig%20Installer.jar?raw=true
- https://drive.google.com/file/d/0B46OxRnier6wSy1ONGhZSzAxSFk/view

Edit with formatting and some more info

**Comment by FlorianWendelborn** [comment]
Thanks, looks good. However, I won't be able to test this, since all of my PCs run some sort of Linux. Maybe someone else could test it though.

**Comment by Aevyz** [comment]
Yeah, hopefully I can get Linux Support soon. Hopefully I won't have to rewrite too much code.

**Comment by FlorianWendelborn** [comment]
@AetherV well, Valve just said FUCK YOUJ to you in particular, I guess.
