### ISSUE TITLE
Support for other keyboard layouts

### ISSUE THREAD

**Issue by hookdump** [dodekeract/manta-config-engine-app#9]
Hi, are you planning on adding other keyboard layouts to the web app? (i.e. spanish, french, maybe even dvorak layout, etc)

I have a Spanish keyboard layout, and while I can use the web app with its US configuration, it would be much much nicer if I could have my own setup. (Also, some keys from the Spanish layout are missing in the US layout).

If you are not planning on doing this, then let me know and I might do it myself and submit as a pull request in case you want to include it in the app.

**Comment by FlorianWendelborn** [comment]
I'm thinking about implementing the ability to switch keyboard layouts for this app. Should drastically improve the user experience. Most likely won't implement other layouts than German and English myself though.

**Comment by hookdump** [comment]
Hey, are you working on this? I would like to help you. (Right now I grabbed a new gamer keyboard, with a few special keys, and I'm about to hardcode the changes in my local app. But if you're working on the keyboard layouts system, I would love to help either finishing it or loading some keyboard layouts).

**Comment by FlorianWendelborn** [comment]
Well. In fact I do have some time to code stuff today. Haven't touched the keyboard thing yet, but give me some hours or a good idea how to do it and I think I can come up with a system that easily allows custom keyboards. In fact I think I got a good idea already. I'll try to find a JSON format to store layouts in and parse them. Should be fairly easy then to create a pull-request with an additional layout.

**Comment by FlorianWendelborn** [comment]
This is my current idea:

```
{
    "language": "en-US",
    "name": "Default Layout (English)",
    "rows": [
        {
            "type": "row",
            "keys": [
                ["empty"],
                ["Esc", "ESC"],
                ["empty", false, 1.5],
                ["F1", "F1"],
                ["F2", "F2"],
                ["F3", "F3"],
                ["F4", "F4"],
                ["empty", false, 0.25],
                ["F5", "F5"],
                ["F6", "F6"],
                ["F7", "F7"],
                ["F8", "F8"],
                ["empty", false, 0.25],
                ["F9", "F9"],
                ["F10", "F10"],
                ["F11", "F11"],
                ["F12", "F12"],
                ["empty", false, 0.5],
                ["Print", false],
                ["Lock", "SCROLLLOCK"],
                ["Pause", "PAUSE"],
                ["empty", false, 4.5]
            ]
        },
        {
            "type": "separator"
        },
        {
            "type": "row"
        },
        {
            "type": "row"
        },
        {
            "type": "row"
        },
        {
            "type": "row"
        },
        {
            "type": "row"
        }
    ]
}
```

Tell me if you find anything wrong with it. I think it should be able to describe every usual keyboard layout.

**Comment by hookdump** [comment]
That's perfect. The third parameter on a key, I assume is the width, with 1 being the normal key width, correct? And that parameter can be used in both empty but also in bound keys, right?

That JSON looks perfect to me.

Let me know how I can help. For example, I can transcribe the current layout to JSON format and post it here. It's a small task, but I want to help, hah.

**Comment by FlorianWendelborn** [comment]
That would be nice. I'll work on the parsing part then. Hate doing repetitive stuff. :)

EDIT: Yes, you're correct. It's `"name", "identity", "width"`. `false` replaces all unknown identities (they currently use `""`).

EDIT2: If you've finished transcribing the format just submit it as a pull-request so you'll be listed as a contributor. I'll push the unfinished layout so you know where to place it.

**Comment by hookdump** [comment]
Cool. I'm on it. A couple regular expressions should take care of this:

```
/<Key name="\([^"]*\)" span="[^"]*" identity="\([^"]*\)"\/>/["\1", "\2"],/g

/<div className="custom-col span_\([0-9]\)-\([0-9]\) key-empty">.*$/["empty", false, \1.\2],/g
```

**Comment by FlorianWendelborn** [comment]
Could you push the layout soon? The parser is ready, but I can't do much more without having the complete layout.

**Comment by hookdump** [comment]
Yup. I'm validating, one sec.

**Comment by hookdump** [comment]
Allrighty.
I haven't triple checked, but it should be OK. I cannot lint the JSON because of the bool and number within the objects, but I think it has no errors.

**Comment by hookdump** [comment]
Updated link, direct raw content:
http://pastebin.com/raw.php?i=ReiDkgTW

Also, is there a reason why = was bound to KEYPAD_= ? that has not worked for me. (I changed it to =, feel free to revert that)

**Comment by FlorianWendelborn** [comment]
Okay, this mostly looks alright. Only thing I noticed is that space is 1 key wide, which it shouldn't be. Other than that it's okay if you just submit this as a pull request now. I can fix/fine tune it once it's in the project files.

EDIT: Also you're using spaces instead of tabs, while this complete repository is using tabs. Will change this later if you don't do it in the pull request.

**Comment by hookdump** [comment]
Cool, I fixed that, and also noticed that I was missing all the widths for non-empty keys that had a width different than 1. Fixed that too. Pull-requesting now...

**Comment by FlorianWendelborn** [comment]
Nice, thanks.

**Comment by hookdump** [comment]
Ok, pull requested.

**Comment by hookdump** [comment]
Oops, I added the file to the root folder, I didn't see you had added a keyboard layouts folder. Remember to move that when you need to test. :)

**Comment by FlorianWendelborn** [comment]
Yeah, already working on it. Also fixed the `\` being unescaped.

**Comment by FlorianWendelborn** [comment]
If you want to you can work on the Spanish layout and submit it as `web/source/keyboard-layouts/es-es.json`. I'm trying to implement a layout switcher and ajax loading of the `.json`s in the meantime. Refer to https://msdn.microsoft.com/en-us/library/39cwe7zf.aspx if you're unsure how to call a keyboard layout.
